# Generated by Django 6.0.7 on 2026-07-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0004_petimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
    ]
