# Generated by Django 6.0.7 on 2026-07-26 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0005_remove_pet_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='petimage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='petimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='adopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(help_text="Free text, e.g. '2 years' or '6 months'.", max_length=50),
        ),
        migrations.AddIndex(
            model_name='adoptionrequest',
            index=models.Index(fields=['status'], name='adoption_request_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['status', 'species'], name='pet_status_species_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner'], name='pet_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='adoptionrequest',
            constraint=models.UniqueConstraint(fields=('pet', 'adopter'), name='unique_adoption_request_per_pet_and_adopter'),
        ),
    ]
